{% set name = "dramatiq" %}
{% set version = "2.2.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9fbbd2feea27b3fa4085446242a24d86f78288b20c78a93f9f0bdbd7d908cd5

build:
  noarch: python
  number: 0
  entry_points:
    - dramatiq = dramatiq.__main__:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - dramatiq
    - dramatiq.brokers
    - dramatiq.middleware
    - dramatiq.rate_limits
    - dramatiq.rate_limits.backends
    - dramatiq.results
    - dramatiq.results.backends
  commands:
    - dramatiq --help

about:
  home: https://dramatiq.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Background Processing for Python 3.
  dev_url: https://github.com/Bogdanp/dramatiq

extra:
  recipe-maintainers:
    - lincrosenbach
    - nicoddemus
